session_name: Dotfiles
start_directory: ./

windows:

  - window_name: Dotfiles
    start_directory: ~/.dotfiles
    layout: main-vertical
    panes:
      - shell_command:
        - nvim
        focus: true
      - shell_command:
        - npm outdated
        - git status
