#!/bin/bash
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Source external scripts.
source $SCRIPT_PATH/scripts/colors

# Install a Homebrew package if not already installed.
function install_brew_pkg() {
  name=$1
  args=$2
  `brew ls | grep -q $name`
  if [ $? == 0 ]; then
    echo -e "${blue}Already installed:${clear} $name"
  else
    if [ $name == 'neovim' ]; then
      brew tap neovim/homebrew-neovim
    fi
    brew install $args $name
  fi
}

# Install a Homebrew Cask package if not already installed.
function install_brew_cask() {
  name=$1
  `brew cask ls | grep -q $name`
  if [ $? == 0 ]; then
    echo -e "${blue}Already installed:${clear} $name"
  else
    brew cask install $name
  fi
}

# Install a Gem if not already installed.
function install_ruby_gem() {
  name=$1
  `gem list --no-versions | grep -q $name`
  if [ $? == 0 ]; then
    echo -e "${blue}Already installed:${clear} $name"
  else
    gem install --user-install $name
  fi
}

# Install a Pip package if not already installed.
function install_pip_pkg() {
  name=$1
  installed=`pip list | grep $name`
  if [[ -z $installed ]]; then
    pip install $name
  else
    echo -e "${blue}Already installed:${clear} $name"
  fi
}

# Install a Pip v3 package if not already installed.
function install_pip3_pkg() {
  name=$1
  installed=`pip3 list | grep $name`
  if [[ -z $installed ]]; then
    pip3 install $name
  else
    echo -e "${blue}Already installed:${clear} $name"
  fi
}

# Homebrew
echo -e "\n${blue}Installing Homebrew packages...${clear}"
if ! type brew > /dev/null; then
  if [[ $OSTYPE == darwin* ]]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
  fi
fi
brew update
if [[ $OSTYPE == darwin* ]]; then
  # Mac specific packages
  install_brew_pkg git
  install_brew_pkg openssl
  install_brew_pkg python
  # NOTE: reattach-to-user-namespace technically no longer needed as of OSX
  # Yosemite, but grunt-concurrent doesn't work in Tmux without it.
  install_brew_pkg reattach-to-user-namespace
else
  # Linux specific packages
  install_brew_pkg git '--with-brewed-curl --with-brewed-openssl'
fi
install_brew_pkg zplug
install_brew_pkg python
install_brew_pkg python3
install_brew_pkg neovim '--HEAD'
install_brew_pkg zsh
install_brew_pkg ctags
install_brew_pkg tmux
install_brew_pkg the_silver_searcher
install_brew_pkg wget
install_brew_pkg docker
install_brew_pkg docker-machine
install_brew_pkg php70
install_brew_pkg php70-msgpack
install_brew_pkg composer
echo -e "${green}Done.${clear}"

# Homebrew Casks
echo -e "\n${blue}Installing Homebrew Casks...${clear}"
brew tap | grep -q caskroom/versions || brew tap caskroom/versions
if [[ $OSTYPE == darwin* ]]; then
  # Mac spcific apps
  install_brew_cask iterm2-beta
  install_brew_cask spectacle
  install_brew_cask flycut
  install_brew_cask sourcetree
  install_brew_cask karabiner
  install_brew_cask vmware-fusion
  install_brew_cask atom
fi
echo -e "${green}Done.${clear}"

# Homebrew cleanup
echo -e "\n${blue}Cleaning up Homebrew installation files...${clear}"
brew cleanup
brew cask cleanup
echo -e "${green}Done.${clear}"

# Use zsh as default shell
echo -e "\n${blue}Setting ZSH as default shell...${clear}"
ZSH_DIR=`which zsh`
DEFAULT_SHELL=`finger $LOGNAME | grep Shell | awk -F': ' '{print $3}'`
if [ $ZSH_DIR == $DEFAULT_SHELL ]; then
  echo -e "${green}Default shell is already ${clear}$DEFAULT_SHELL${green}.${clear}"
else
  chsh -s `which zsh`
  echo -e "${green}Done.${clear}"
fi

# Global .gitignore
echo -e "\n${blue}Setting global Git ignore file path...${clear}"
git config --global core.excludesfile ~/.gitignore
echo -e "${green}Done.${clear}"

# Git submodules
echo -e "\n${blue}Installing Git submodules...${clear}"
git submodule init
git submodule update --remote --rebase
echo -e "${green}Done.${clear}"

# Fonts
source $SCRIPT_PATH/install-fonts

# iTerm CLI
if [[ $OSTYPE == darwin* ]]; then
  echo -e "\n${blue}Installing iTerm cli integration...${clear}"
  ITERM_CLI_PATH=~/.iterm2_shell_integration.zsh
  if [ -e "$ITERM_CLI_PATH" ]; then
    echo -e "${green}Already installed.${clear}"
  else
    curl -L iterm2.com/misc/install_shell_integration.sh | bash
    echo -e "${green}Done.${clear}"
  fi
fi

# Ruby Gems
echo -e "\n${blue}Installing Ruby gems...${clear}"
install_ruby_gem CoffeeTags
install_ruby_gem neovim
echo -e "${green}Done.${clear}"

# PIP packages
echo -e "\n${blue}Installing PIP packages...${clear}"
install_pip_pkg neovim
install_pip_pkg awscli
install_pip_pkg tmuxp
install_pip_pkg docker-compose
install_pip3_pkg neovim
echo -e "${green}Done.${clear}"

# Tmux plugins
echo -e "\n${blue}Installing Tmux plugins...${clear}"
$SCRIPT_PATH/libs/tpm/bin/clean_plugins
$SCRIPT_PATH/libs/tpm/bin/install_plugins
echo -e "${green}Done.${clear}"

# Vim-Plug
echo -e "\n${blue}Installing Vim-Plug...${clear}"
VIMPLUG_PATH=~/.config/nvim/autoload/plug.vim
if [ -e "$VIMPLUG_PATH" ]; then
  echo -e "${green}Already installed.${clear}"
else
  curl -fLo $VIMPLUG_PATH --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  echo -e "${green}Done.${clear}"
fi

# Vim plugins
echo -e "\n${blue}Starting NeoVim and installing plugins...${clear}"
nvim +PlugInstall +qall
echo -e "${green}Done.${clear}"

# ZSH plugins
echo -e "\n${blue}Installing ZSH plugins...${clear}"
ZPLUG_HOME=`brew --prefix zplug`
zplug install
zplug load --verbose
echo -e "${green}Done.${clear}"

# Create symlinks
source $SCRIPT_PATH/link

echo -e "${green}All done.${clear}\n"
