#!/bin/bash
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Source external scripts.
source $SCRIPT_PATH/scripts/colors

if [[ $OSTYPE == darwin* ]]; then
  echo -e "\n${blue}Updating icon font...${clear}"
  FONT=Sauce\ Code\ Pro\ Nerd\ Font\ Complete.ttf
  FONT_PATH=$SCRIPT_PATH/themes/nerd-fonts/patched-fonts/SourceCodePro/Regular/complete/$FONT
  cp "$FONT_PATH" ~/Library/Fonts
  echo -e "${green}Done.${clear}\n"
fi
