#!/bin/bash
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Source external scripts.
source $SCRIPT_PATH/scripts/colors

# Make sure XDG config directores exist.
mkdir -p ~/.config/nvim

echo -e "\n${blue}Linking dotfiles into your user directory...${clear}"
ln -sfhv $SCRIPT_PATH/agignore ~/.agignore
ln -sfhv $SCRIPT_PATH/gitconfig ~/.gitconfig
ln -sfhv $SCRIPT_PATH/gitignore ~/.gitignore
ln -sfhv $SCRIPT_PATH/tmux.conf ~/.tmux.conf
ln -sfhv $SCRIPT_PATH/zlogin ~/.zlogin
ln -sfhv $SCRIPT_PATH/zshrc ~/.zshrc
ln -sfhv $SCRIPT_PATH/init.vim ~/.config/nvim/init.vim
echo -e "${green}✔${clear}"

echo ""
