#!/bin/zsh
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Source external scripts.
source $SCRIPT_PATH/scripts/colors

# Homebrew
echo -e "\n${blue}Updating Homebrew packages...${clear}"
brew update
brew upgrade --all
brew cleanup
echo -e "${green}Done.${clear}"

# NeoVim
echo -e "\n${blue}Updating NeoVim to latest HEAD...${clear}"
NEOVIM_REPO_PATH=/Library/Caches/Homebrew/neovim--git/
NEOVIM_LOCAL_SHA=`cd $NEOVIM_REPO_PATH && git rev-parse @`
NEOVIM_REMOTE_SHA=`cd $NEOVIM_REPO_PATH && git fetch && git rev-parse @{u}`
if [[ $NEOVIM_LOCAL_SHA == $NEOVIM_REMOTE_SHA ]]; then
  echo -e "${green}NeoVim already up to date.${clear}"
else
  brew reinstall --HEAD neovim
  echo -e "\n${green}Done.${clear}"
fi

# pip
echo -e "\n${blue}Updating certain pip packages...${clear}"
pip install -U pip neovim awscli tmuxp
echo -e "${green}Done.${clear}"

# gem
echo -e "\n${blue}Updating certain ruby gems...${clear}"
gem update CoffeeTags
echo -e "${green}Done.${clear}"

# Git submodules
echo -e "\n${blue}Updating git submodules...${clear}"
git submodule update --remote --rebase
echo -e "${green}Done.${clear}"

# zgen
echo -e "\n${blue}Updating zgen...${clear}"
source ~/.dotfiles/libs/zgen/zgen.zsh
zgen-selfupdate
echo -e "${green}Done.${clear}"

echo -e "\n${blue}Updating zgen plugins...${clear}"
zgen-update
#zgen-save # For some reason this breaks the zsh template...
echo -e "${green}Done.${clear}"

echo -e "\n💻  ${blue}You should start a new terminal session now.${clear}"

echo ""
