#!/bin/bash
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Colors
blue=`tput setaf 4 2>/dev/null`
green=`tput setaf 2 2>/dev/null`
red=`tput setaf 1 2>/dev/null`
clear=`tput sgr0 2>/dev/null`


## Functions ##

# Install a package using the given arguments if not already installed.
function install_pkg() {
  bin=$1
  list_cmd=$2
  install_cmd=$3
  name=$4
  args=$5
  $bin $list_cmd 2>/dev/null | grep -q $name
  if [ $? == 0 ]; then
    echo -e "$name ${blue}already installed with ${clear}$bin"
  else
    echo -e "${blue}Installing ${clear}$name${blue}...${clear}"
    $bin $install_cmd $args $name
  fi
}

# Add a Homebrew tap if not already added.
function install_tap() {
  tap=$1
  brew tap | grep -q $tap
  if [ $? == 0 ]; then
    echo -e "$tap ${blue}already tapped${clear}"
  else
    echo -e "${blue}Adding ${clear}$tap${blue} tap...${clear}"
    brew tap $tap
  fi
}


## Homebrew ##

# Install Homebrew
echo -ne "\n${blue}Installing Homebrew...${clear}"
if ! type brew > /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || exit $?
  echo -e "\n${green}✔${clear}"
else
  echo -e "${green} ✔ already installed${clear}"
fi

# Install packages
echo -e "\n${blue}Installing Homebrew packages...${clear}"
brew update
install_pkg brew ls install git
install_pkg brew ls install antidote
install_pkg brew ls install jq
install_pkg brew ls install neovim
install_pkg brew ls install the_silver_searcher
install_pkg brew ls install ripgrep
install_pkg brew ls install wget
install_pkg brew ls install asdf
install_pkg brew ls install azure-cli
echo -e "${green}✔${clear}"

# Cleanup
echo -e "\n${blue}Cleaning up Homebrew installation files...${clear}"
brew cleanup
echo -e "${green}✔${clear}"

# Create symlinks
source $SCRIPT_PATH/link

echo -e "🍕 ${green}All done!${clear} 🍕\n"
