#!/bin/zsh
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Colors
blue=`tput setaf 4 2>/dev/null`
green=`tput setaf 2 2>/dev/null`
red=`tput setaf 1 2>/dev/null`
clear=`tput sgr0 2>/dev/null`

# Update a `HEAD` brew package if there are remote changes available.
function update_brew_pkg_head() {
  pkg_name=$1
  echo -en "\n${blue}Updating ${clear}$pkg_name${blue} to latest HEAD...${clear} "
  repo_path=~/Library/Caches/Homebrew/$pkg_name--git/
  local_sha=`cd $repo_path && git rev-parse @`
  remote_sha=`cd $repo_path && git fetch && git rev-parse @{u}`
  if [[ $local_sha == $remote_sha ]]; then
    echo -e "${green}✔${clear}"
  else
    echo ""
    brew reinstall $pkg_name
    echo -e "${green}✔${clear}"
  fi
}

# Homebrew
echo -e "\n${blue}Updating Homebrew packages...${clear}"
brew update
brew upgrade
brew cleanup
echo -e "${green}✔${clear}"

# Vim plugins
# echo -en "\n${blue}Updating Vim plugins...${clear} "
# nvim +PlugUpgrade +PlugUpdate +qall
# echo -e "${green}✔${clear}"

# Git submodules
# echo -e "\n${blue}Updating Git submodules...${clear}"
# cd $SCRIPT_PATH/..
# git submodule update --remote --rebase
# cd $SCRIPT_PATH
# echo -e "${green}✔${clear}"

# Gem
# echo -e "\n${blue}Updating Ruby gems...${clear}"
# gem update
# echo -e "${green}✔${clear}"

# Pip
# echo -e "\n${blue}Updating certain PIP packages...${clear}"
# pip3 install -U pip neovim pynvim tmuxp
# echo -e "${green}✔${clear}"

# Tmux plugins
# echo -e "\n${blue}Updating Tmux plugins...${clear}"
# $SCRIPT_PATH/../libs/tpm/bin/clean_plugins
# $SCRIPT_PATH/../libs/tpm/bin/update_plugins all
# echo -e "${green}✔${clear}"

# zplug
# echo -e "\n${blue}Updating ZSH plugins...${clear}"
# export ZPLUG_HOME=~/.config/zplug
# source `brew --prefix zplug`/init.zsh
# source $SCRIPT_PATH/../plugins.zsh
# zplug load
# zplug update
# zplug clear
# echo -e "${green}✔${clear}"

echo -e "\n🍕 ${green}All done${clear} 🍕"

echo ""
